### ISSUE TITLE
输入输出尺寸不同

### ISSUE THREAD

**Issue by SmartLhl** [NamecantbeNULL/MCDRNet#1]
请问我用您公布的模型测试sir数据，sir分辨率是540*400，为什么输出结果是640*448？

**Comment by NamecantbeNULL** [comment]
> 请问我用您公布的模型测试sir数据，sir分辨率是540_400，为什么输出结果是640_448？

我们的模型要求图片分辨率是32的整数倍，为了保证文中比较的多个数据集分辨率统一，我们保持原图长宽比取长边为640进行resize。
